# Generated by Django 5.1.7 on 2025-03-23 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="product name")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="product description"),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="product price",
                    ),
                ),
                ("image", models.ImageField(blank=True, upload_to="products/")),
            ],
        ),
    ]
