# Generated by Django 5.1.7 on 2025-03-24 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["name"],
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
            },
        ),
    ]
